/* ARCHITECTURE IMAGES */
import badshahiMosque from "../assets/img/display-paintings/architecture/asia-badshahi-mosque.png";
import kaabahArchitecture from "../assets/img/display-paintings/architecture/kaaba-painting.png";
import badshahiMosque1 from "../assets/img/display-paintings/architecture/badshahi-mosque.png";
import delhiMosque from "../assets/img/display-paintings/architecture/delhi-mosque.jpg";
import jalilKhayatMosque from "../assets/img/display-paintings/architecture/middle-east-jalil-khayat-mosque.png";
import abstractMosque1 from "../assets/img/display-paintings/architecture/mosque-1.jpg";
import abstractMosque2 from "../assets/img/display-paintings/architecture/mosque-2.jpg";
import abstractMosque3 from "../assets/img/display-paintings/architecture/mosque-3.jpg";
import abstractMosque4 from "../assets/img/display-paintings/architecture/mosque-4.jpg";

/* CALLIGRAPHY IMAGES */
import alhamdulillah from "../assets/img/display-paintings/calligraphy/alhamdulillah.png";
import AllahImg from "../assets/img/display-paintings/calligraphy/allah.png";
import AllahuAkbarImg from "../assets/img/display-paintings/calligraphy/allahu-akbar.png";
import ayatulkursi from "../assets/img/display-paintings/calligraphy/ayatul-kursi.png";
import ayatulkursi1 from "../assets/img/display-paintings/calligraphy/ayatul-kursi-2.png";
import bismillah from "../assets/img/display-paintings/calligraphy/bismillah.png";
import rabbana from "../assets/img/display-paintings/calligraphy/dua-rabbana.jpg";
import hasbunallah from "../assets/img/display-paintings/calligraphy/hasbunallahu-wa-nimalwakeel.png";
import muhammad from "../assets/img/display-paintings/calligraphy/muhammad.png";
import disposerOfAffairs from "../assets/img/display-paintings/calligraphy/quran-allah-is-best-disposer-of-affairs.jpg";
import inTheRemembrance from "../assets/img/display-paintings/calligraphy/quran-verily-in-the-remembrance.jpg";
import subhanallah from "../assets/img/display-paintings/calligraphy/subhanallah.png";

/* GEOMETRIC IMAGES */
import arabesque1 from "../assets/img/display-paintings/geometric/arabesque-1.png";
import arabesque2 from "../assets/img/display-paintings/geometric/arabesque-2.png";
import arabesque3 from "../assets/img/display-paintings/geometric/arabesque-3.png";
import arabesque4 from "../assets/img/display-paintings/geometric/arabesque-4.png";
import moroccan1 from "../assets/img/display-paintings/geometric/moroccan-wall-art.jpg";
import moroccan2 from "../assets/img/display-paintings/geometric/moroccan-wall-art-2.jpg";
import moroccan3 from "../assets/img/display-paintings/geometric/moroccan-wall-art-3.jpg";

export const data = [
    {
        title: "Badshahi Mosque",
        img: badshahiMosque,
        price: 45.0,
        categories: [
            "Architecture",
            "Asian Architecture",
            "Single",
            "Orange",
            "Black",
            "Brown",
            "<$50",
        ],
        rating: 4.7,
        numOfReviews: 243,
        id: 0,
    },
    {
        title: "Kaabah Architecture",
        img: kaabahArchitecture,
        price: 55.0,
        categories: [
            "Architecture",
            "Middle Eastern Architecture",
            "Single",
            "Yellow",
            "Black",
            "White",
            "$50 - $100",
        ],
        rating: 5,
        numOfReviews: 453,
        id: 1,
    },
    {
        title: "Badshahi Mosque",
        img: badshahiMosque1,
        price: 55.0,
        categories: [
            "Architecture",
            "Middle Eastern Architecture",
            "Geometric Shapes",
            "Single",
            "Brown",
            "White",
            "Yellow",
            "$50 - $100",
        ],
        rating: 5,
        numOfReviews: 453,
        id: 2,
    },
    {
        title: "Delhi Mosque",
        img: delhiMosque,
        price: 35.0,
        categories: [
            "Architecture",
            "Asian Architecture",
            "Single",
            "Orange",
            "White",
            "Blue",
            "<$50",
        ],
        rating: 3.5,
        numOfReviews: 55,
        id: 3,
    },
    {
        title: "Jalil Khayat Mosque",
        img: jalilKhayatMosque,
        price: 75.0,
        categories: [
            "Architecture",
            "Middle Eastern Architecture",
            "Single",
            "Blue",
            "Brown",
            "Green",
            "$50 - $100",
        ],
        rating: 4.8,
        numOfReviews: 355,
        id: 4,
    },
    {
        title: "Mosque Architecture Moon",
        img: abstractMosque1,
        price: 120.0,
        categories: [
            "Architecture",
            "Middle Eastern Architecture",
            "Single",
            "Blue",
            "Brown",
            "Orange",
            "$100 - $200",
        ],
        rating: 4.6,
        numOfReviews: 234,
        id: 5,
    },
    {
        title: "Mosque Architecture Symmetrical",
        img: abstractMosque2,
        price: 175.0,
        categories: [
            "Architecture",
            "Middle Eastern Architecture",
            "Single",
            "Blue",
            "Brown",
            "Orange",
            "$100 - $200",
        ],
        rating: 4.3,
        numOfReviews: 434,
        id: 6,
    },
    {
        title: "Mosque Architecture Bridge",
        img: abstractMosque3,
        price: 175.0,
        categories: [
            "Architecture",
            "Middle Eastern Architecture",
            "Single",
            "Blue",
            "Brown",
            "Orange",
            "$100 - $200",
        ],
        rating: 4.8,
        numOfReviews: 342,
        id: 7,
    },
    {
        title: "Mosque Architecture Shapes",
        img: abstractMosque4,
        price: 175.0,
        categories: [
            "Architecture",
            "Middle Eastern Architecture",
            "Single",
            "Blue",
            "Brown",
            "Orange",
            "$100 - $200",
        ],
        rating: 4.8,
        numOfReviews: 355,
        id: 8,
    },
    {
        title: "Alhamdulillah Calligraphy",
        img: alhamdulillah,
        price: 75.0,
        categories: [
            "Calligraphy",
            "Popular Duas",
            "Sayings",
            "Single",
            "Green",
            "Yellow",
            "$50 - $100",
        ],
        rating: 3.8,
        numOfReviews: 50,
        id: 9,
    },
    {
        title: "Allah Calligraphy",
        img: AllahImg,
        price: 125.0,
        categories: [
            "Calligraphy",
            "Sayings",
            "Single",
            "Green",
            "Grey",
            "$100 - $200",
        ],
        rating: 4.5,
        numOfReviews: 132,
        id: 10,
    },
    {
        title: "Allahu Akbar Calligraphy",
        img: AllahuAkbarImg,
        price: 45.0,
        categories: ["Calligraphy", "Sayings", "Single", "Yellow", "<$50"],
        rating: 4.2,
        numOfReviews: 12,
        id: 11,
    },
    {
        title: "Ayatul-Kursi White",
        img: ayatulkursi,
        price: 115.0,
        categories: [
            "Calligraphy",
            "Popular Duas",
            "Islamic Verses",
            "Single",
            "White",
            "Green",
            "Gold",
            "$100 - $200",
        ],
        rating: 4.5,
        numOfReviews: 234,
        id: 12,
    },
    {
        title: "Ayatul-Kursi Gold",
        img: ayatulkursi1,
        price: 115.0,
        categories: [
            "Calligraphy",
            "Popular Duas",
            "Islamic Verses",
            "Single",
            "Orange",
            "Gold",
            "Brown",
            "$100 - $200",
        ],
        rating: 4.4,
        numOfReviews: 125,
        id: 13,
    },
    {
        title: "Bismillah Calligraphy",
        img: bismillah,
        price: 150.0,
        categories: [
            "Calligraphy",
            "Popular Duas",
            "Islamic Verses",
            "Sayings",
            "Single",
            "Brown",
            "Silver",
            "$100 - $200",
        ],
        rating: 4.8,
        numOfReviews: 355,
        id: 14,
    },
    {
        title: "Dua Rabbana",
        img: rabbana,
        price: 175.0,
        categories: [
            "Calligraphy",
            "Popular Duas",
            "Single",
            "Brown",
            "Orange",
            "$100 - $200",
        ],
        rating: 4.8,
        numOfReviews: 355,
        id: 15,
    },
    {
        title: "Hasbunallahu Wa Ni'mal Wakeel",
        img: hasbunallah,
        price: 123.0,
        categories: [
            "Calligraphy",
            "Popular Duas",
            "Sayings",
            "Single",
            "Blue",
            "Red",
            "Green",
            "Orange",
            "Black",
            "$100 - $200",
        ],
        rating: 4.3,
        numOfReviews: 76,
        id: 16,
    },
    {
        title: "Prophet Muhammad (PBUH)",
        img: muhammad,
        price: 75.0,
        categories: [
            "Calligraphy",
            "Sayings",
            "Single",
            "Green",
            "Brown",
            "$50 - $100",
        ],
        rating: 4.5,
        numOfReviews: 123,
        id: 17,
    },
    {
        title: "Allah is the best Disposer of Affairs",
        img: disposerOfAffairs,
        price: 175.0,
        categories: [
            "Calligraphy",
            "Popular Duas",
            "Islamic Verses",
            "Sayings",
            "Single",
            "Blue",
            "Brown",
            "Orange",
            "$100 - $200",
        ],
        rating: 4.8,
        numOfReviews: 355,
        id: 18,
    },
    {
        title: "Verily in the Remembrance of Allah",
        img: inTheRemembrance,
        price: 145.0,
        categories: [
            "Calligraphy",
            "Popular Duas",
            "Islamic Verses",
            "Sayings",
            "Single",
            "Blue",
            "Brown",
            "$100 - $200",
        ],
        rating: 4.8,
        numOfReviews: 355,
        id: 19,
    },
    {
        title: "Subhanallah Calligraphy",
        img: subhanallah,
        price: 75.0,
        categories: [
            "Calligraphy",
            "Sayings",
            "Popular Duas",
            "Single",
            "Green",
            "$50 - $100",
        ],
        rating: 4.8,
        numOfReviews: 45,
        id: 20,
    },
    {
        title: "Arabesque Square",
        img: arabesque1,
        price: 275.0,
        categories: [
            "Geometric",
            "Vegetal Patterns",
            "Single",
            "Green",
            "Blue",
            "Yellow",
            "$200+",
        ],
        rating: 4.8,
        numOfReviews: 523,
        id: 21,
    },
    {
        title: "Arabesque Circle",
        img: arabesque2,
        price: 225.0,
        categories: [
            "Geometric",
            "Vegetal Patterns",
            "Single",
            "Green",
            "Red",
            "Yellow",
            "Blue",
            "Black",
            "Brown",
            "$200+",
        ],
        rating: 4.9,
        numOfReviews: 454,
        id: 22,
    },
    {
        title: "Arabesque Diamond",
        img: arabesque3,
        price: 245.0,
        categories: [
            "Geometric",
            "Calligraphy",
            "Vegetal Patterns",
            "Single",
            "Red",
            "Yellow",
            "Blue",
            "$200+",
        ],
        rating: 4.8,
        numOfReviews: 245,
        id: 23,
    },
    {
        title: "Arabesque Abstract",
        img: arabesque4,
        price: 205.0,
        categories: [
            "Geometric",
            "Calligraphy",
            "Single",
            "Vegetal Patterns",
            "Brown",
            "Yellow",
            "Orange",
            "$200+",
        ],
        rating: 4.8,
        numOfReviews: 415,
        id: 24,
    },
    {
        title: "Moroccan Art",
        img: moroccan1,
        price: 75.0,
        categories: [
            "Geometric",
            "Geometric Shapes",
            "Single",
            "Blue",
            "Red",
            "Orange",
            "$50 - $100",
        ],
        rating: 4.8,
        numOfReviews: 145,
        id: 25,
    },
    {
        title: "Moroccan Shapes",
        img: moroccan2,
        price: 85.0,
        categories: [
            "Geometric",
            "Geometric Shapes",
            "Single",
            "Green",
            "Red",
            "Orange",
            "$50 - $100",
        ],
        rating: 4.3,
        numOfReviews: 324,
        id: 26,
    },
    {
        title: "Moroccan Pattern",
        img: moroccan3,
        price: 76.0,
        categories: [
            "Geometric",
            "Geometric Shapes",
            "Single",
            "Green",
            "Brown",
            "Yellow",
            "Orange",
            "$50 - $100",
        ],
        rating: 4.5,
        numOfReviews: 123,
        id: 27,
    },
];
